name: Build for Xiaomi AX6S
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout cloudflared
       uses: actions/checkout@v3
       with:
         path: cloudflared
     - name: Install OpenWrt SDK
       run: |
         wget -O sdk.tar.xz https://downloads.openwrt.org/releases/22.03.2/targets/mediatek/mt7622/openwrt-sdk-22.03.2-mediatek-mt7622_gcc-11.2.0_musl.Linux-x86_64.tar.xz
         tar -xf sdk.tar.xz
         mv openwrt-sdk-22.03.2-mediatek-mt7622_gcc-11.2.0_musl.Linux-x86_64 sdk
         cd ./sdk
         ln -s "$GITHUB_WORKSPACE/cloudflared" -t ./package
         ./scripts/feeds update -a
     - name: Compile
       run: |
         cd ./sdk
         cp ./package/cloudflared/.config ./
         make package/cloudflared/compile
     - name: Archive build result
       uses: actions/upload-artifact@v3
       with:
         name: cloudflared
         path: sdk/bin/packages/aarch64_cortex-a53/base/*
